fixtures:
  repositories:
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: "4.15.0"
    nodejs:
      repo: "https://github.com/ipcrm/puppet-nodejs.git"
      ref: "windows_npm"
    app_modeling:
      repo: "https://github.com/puppetlabs/puppetlabs-app_modeling.git"
      ref: "0.2.0"
    vcsrepo:
      repo: "https://github.com/puppetlabs/puppetlabs-vcsrepo.git"
      ref: "1.5.0"
    chocolatey:
      repo: "https://github.com/puppetlabs/puppetlabs-chocolatey"
      ref: "2.0.1"
  symlinks:
    nodejs_app: "#{source_dir}"
    nodejs: "/Users/mcadorette/git/nodejs"
